<?php

namespace app\admin\controller;

use app\admin\middleware\CheckLogin;
use app\common\model\Manage as ManageModel;

use app\BaseController;

/**
 * 后台-控制器
 * @author 鱼鱼鱼
 * @since 2023年8月3日14:27:49
 * Class Backend
 * @package app\admin\controller
 */
class Backend extends BaseController
{
    // 模型
    protected $model;
    // 服务
    protected $service;
    // 用户ID
    protected $userId;
    // 登录信息
    protected $userInfo;
    // 中间件
    protected $middleware = [
        CheckLogin::class
    ];

    /**
     * 初始化
     * @author 鱼鱼鱼
     * @since 2023年8月3日14:27:54
     */
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub

        // 获取Token
        $token = request()->header("Authorization");
        if ($token) {
            $user = ManageModel::where(['token' => $token])->find();
            if (!$user) {
                return message("登录失效", false, [], 401);
            }
            $this->userId = $user['id'];
            $this->userInfo = $user;
        }
    }
}